"""empty message

Revision ID: b9266c5be1ec
Revises: b97b2cb0830b
Create Date: 2025-08-31 00:49:38.697965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9266c5be1ec'
down_revision: Union[str, Sequence[str], None] = 'b97b2cb0830b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agency_snapshot_id'), table_name='agency')
    op.drop_index(op.f('ix_calendar_snapshot_id'), table_name='calendar')
    op.drop_index(op.f('ix_calendar_dates_snapshot_id'), table_name='calendar_dates')
    op.drop_index(op.f('ix_fare_attributes_snapshot_id'), table_name='fare_attributes')
    op.drop_index(op.f('ix_fare_rules_snapshot_id'), table_name='fare_rules')
    op.drop_index(op.f('ix_feed_info_snapshot_id'), table_name='feed_info')
    op.drop_index(op.f('ix_routes_snapshot_id'), table_name='routes')
    op.drop_index(op.f('ix_shapes_snapshot_id'), table_name='shapes')
    op.drop_index(op.f('ix_shapes_snapshot_lat_lon'), table_name='shapes')
    op.drop_index(op.f('ix_stop_times_snapshot_id'), table_name='stop_times')
    op.drop_index(op.f('ix_stops_snapshot_id'), table_name='stops')
    op.drop_index(op.f('ix_stops_snapshot_lat_lon'), table_name='stops')
    op.drop_index(op.f('ix_trips_snapshot_id'), table_name='trips')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_trips_snapshot_id'), 'trips', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_stops_snapshot_lat_lon'), 'stops', ['snapshot_id', 'stop_lat', 'stop_lon'], unique=False)
    op.create_index(op.f('ix_stops_snapshot_id'), 'stops', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_stop_times_snapshot_id'), 'stop_times', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_shapes_snapshot_lat_lon'), 'shapes', ['snapshot_id', 'shape_pt_lat', 'shape_pt_lon'], unique=False)
    op.create_index(op.f('ix_shapes_snapshot_id'), 'shapes', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_routes_snapshot_id'), 'routes', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_feed_info_snapshot_id'), 'feed_info', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_fare_rules_snapshot_id'), 'fare_rules', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_fare_attributes_snapshot_id'), 'fare_attributes', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_calendar_dates_snapshot_id'), 'calendar_dates', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_calendar_snapshot_id'), 'calendar', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_agency_snapshot_id'), 'agency', ['snapshot_id'], unique=False)
    # ### end Alembic commands ###
