"""change_stop_times_to_string_for_gtfs_24h_support

Revision ID: b97b2cb0830b
Revises: ec75890a553c
Create Date: 2025-08-18 15:12:55.969951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b97b2cb0830b'
down_revision: Union[str, Sequence[str], None] = 'ec75890a553c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stop_times', 'arrival_time',
               existing_type=postgresql.TIME(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('stop_times', 'departure_time',
               existing_type=postgresql.TIME(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stop_times', 'departure_time',
               existing_type=sa.String(),
               type_=postgresql.TIME(),
               existing_nullable=True)
    op.alter_column('stop_times', 'arrival_time',
               existing_type=sa.String(),
               type_=postgresql.TIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
