name: Build and Push Docker image

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}
          VERSION=latest
          COMMIT_SHA=${{ github.sha}}

          docker build . -f Dockerfile.prod -t $IMAGE_ID:$VERSION -t $IMAGE_ID:$COMMIT_SHA

      - name: Push Docker image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}

          docker push --all-tags $IMAGE_ID
